I/O-Record Support
tud-zih-energy/otf2xx pull request #3
Opened 2017-09-12 19:00 UTC by blastmaster

These commits adds support for the OTF2 I/O-Records.
Trace writing functionality is untested and there are still some TODOs.
Trace readings seems to work fine ;)

2017-09-13 11:52 UTC, bmario requested changes
Looks good overall, but I wonder if there are more changes in OTF2 2.1 we need to address prior to bumping the version to it.

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/writer/global.hpp
> +        ~global() //TODO
We REALLY need to fix the missing store calls.
Definitions with one id space in a single `store(...)`

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/attribute_list.hpp
> +            static_assert(Test, "Not implemented yet.");
We need to fix that

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/attribute_list.hpp
> +            static_assert(Test, "Not implemented yet.");
We need to fix that

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/definition/detail/io_handle_base.hpp
> +        {
If I understand the documentation right, these work like properties, i.e., each IoHandlePerCreatedState references exactly one IoHandle definition. So they don't occupy the same ID space, thus this isn't needed.

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/definition/detail/io_pre_created_handle_state_impl.hpp
> +            //io_pre_created_handle_state_impl(const otf2::definition::io_handle& handle,
This should use the the commented out code.

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/definition/io_pre_created_handle_state.hpp
> +        //io_pre_created_handle_state(const otf2::definition::io_handle& handle,
Should use the commented out code instead

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/definition/pre_fwd.hpp
> +        class io_handle_base;
not needed

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/definition/pre_fwd.hpp
> +    using io_file_property = property<io_file>;
This looks suspicious, as io_file is polymorphic in OTF2. A property on a polymorphic definition is a new thing, we may end up for this PR to add a KNOWN_ISSUE.

2017-09-13 11:52 UTC, bmario commented on include/otf2xx/writer/global.hpp
> +                        NULL, NULL, NULL),  //TODO: we doesn't have these arguments.
We need to add these...

2017-09-14 08:09 UTC, blastmaster commented on include/otf2xx/writer/global.hpp
> +        ~global() //TODO
Right, I was not sure if the order of store calls matter?

2017-09-14 13:25 UTC, bmario commented on include/otf2xx/attribute_list.hpp
> +            static_assert(Test, "Not implemented yet.");
Okay, this is actually worth a separate issue. There isn't a quick fix for that.

2017-09-14 13:26 UTC, bmario commented on include/otf2xx/writer/global.hpp
> +        ~global() //TODO
Yes, the sequence does matter.

2018-01-09 09:53 UTC, merged